blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/westpoint-io/dustoff/discussions
    about: Ask questions or start a discussion here instead of opening an issue.
